export const Label = {
  title: "Guiding Mother",
  selectCampus: "Select Campus",
  loginHeader: "Login with account belonging to the school",
  signIn: "Sign In",
  forgotPassword: "Forgot Password?",
  forgotPasswordHeader: "Please enter an email associated with your account",
  submit: "Submit",
  student: "Student",
  attendance: "Attendance",
  timetable: "Timetable",
  reportCard: "Report Card",
  payment: "Payment",
  updatePassword: "Update Password",
  profile: "Profile",
  logout: "Log Out",
  studentList: "Student List",
  selectClass: "Select Class",
  attendance: "Attendance",
  totalPresent: "Total Present",
  totalAbsent: "Total Absent",
  presentList: "Present List",
  absentList: "Absent List",
  pdfDownload: "PDF Download",
  updatePasswordHeader: "Please enter at least 8 characters",
  update: "Update",
  noticeList: "Notice List",
  notice: "Notice",
  personalInfo: "Personal Information",
  contactInfo: "Contact Information",
  chooseChildHeader: "You can choose the information of your child that you want to see.",
  bookList: "Book List",
  studentInfo: "Student Information",
  parentInfo: "Parent Information",
  attendanceList: "Attendance List for ",
  courseList: 'Course',
  outcomeList: 'Outcome',
}